.github/actions/node/build/action.yml
.github/workflows/node-step-azure-storage-build-and-deploy.yml
.github/workflows/node-step-docker-build-and-push-image.yml
.github/workflows/node-step-format-lint-build.yml
.github/workflows/node-step-test-cypress.yml
.github/workflows/node-workflow-common.yml
README.md

This adds support to NX projects where multiple applications under the same node projects exist.

feat(MIGI-56): add support to multiple app in node

---

.github/actions/dotnet/format/action.yml
.github/workflows/dotnet-workflow-common.yml
README.md

feat: add .net formatter version choice

---

.github/workflows/conventional-commits-step-lint.yml
.github/workflows/sonar-step-analyze.yml
docker/sonar-scanner-cli/Dockerfile
docker/sonar-scanner-cli/build.sh

ci: add sonar analyze flutter support

---

README.md

docs: add sonar with flutter example

---

.github/workflows/conventional-commits-step-lint.yml

fix: move conventional commits step lint to containers

---

.github/workflows/docker-step-build-and-push-image.yml
.github/workflows/node-step-docker-build-and-push-image.yml
README.md

feat: add checkout ref to docker and node workflows

---

.github/workflows/sonar-step-dotnet-analyze.yml

feat: handle multiple dotnet test coverage results

---

.github/actions/node/build/action.yml
.github/workflows/node-step-azure-storage-build-and-deploy.yml

feat: remove checkout from node build

---

.github/workflows/node-step-docker-build-and-push-image.yml

fix: add missing checkout to node docker workflow

---

.github/workflows/sonar-step-flutter-analyze.yml

ci: update flutter workflows

---

.github/workflows/node-step-format-lint-build.yml

fix: node step format

---

.github/workflows/sonar-step-analyze.yml
.github/workflows/sonar-step-dotnet-analyze.yml
.github/workflows/sonar-step-flutter-analyze.yml
README.md

fix: sonarQube

---

.github/actions/sonar/analyze/action.yml
.github/workflows/sonar-step-analyze.yml

fix: update action sonar

---

.github/workflows/jira-step-move-issue.yml

fix: fix jira step move issue workflow

---

.github/workflows/conventional-commits-step-release.yml
.github/workflows/django-step-lint-check.yml
.github/workflows/django-step-tests.yml
.github/workflows/docker-step-build-and-push-image.yml
.github/workflows/docker-step-deploy.yml
.github/workflows/dotnet-step-azure-webapp-build-and-deploy.yml
.github/workflows/dotnet-workflow-common.yml
.github/workflows/node-step-azure-storage-build-and-deploy.yml
.github/workflows/node-step-docker-build-and-push-image.yml
.github/workflows/node-step-format-lint-build.yml
.github/workflows/node-step-test-cypress.yml
.github/workflows/python-azure-function-build-and-deploy.yml
.github/workflows/release.yml
.github/workflows/sonar-step-analyze.yml
.github/workflows/sonar-step-dotnet-analyze.yml
.github/workflows/sonar-step-flutter-analyze.yml
.github/workflows/springboot-step-docker-build-and-push-image.yml
.github/workflows/springboot-step-lint-check.yml
.github/workflows/springboot-step-tests.yml
README.md

feat(ZCH-70): update checkout action from v3 to v4

---

.github/actions/docker/deploy/action.yml
.github/workflows/docker-step-deploy.yml

fix(ZCH-83): allow deploy for runner without groups

---

.github/workflows/sonar-step-springboot-analyze.yml
.github/workflows/springboot-step-tests-mysql.yml
.github/workflows/springboot-step-tests.yml
.github/workflows/springboot-workflow-common.yml

chore: add mysql support + restore sonar for springboot

---

.github/workflows/springboot-step-docker-build-and-push-image.yml

fix: fix for release

---

.github/workflows/dotnet-workflow-common.yml
.github/workflows/sonar-step-dotnet-analyze.yml

chore: add dotnet sonar quality gate check

---

.github/workflows/node-step-format-lint-build.yml

fix: update npm cache directory

---

.github/workflows/dotnet-step-azure-webapp-build-and-deploy.yml
.github/workflows/node-step-azure-storage-build-and-deploy.yml
README.md

fix: azure cli container version upgrade to support az storage copy

---

.github/actions/maven/settings/action.yaml
.github/workflows/sonar-step-springboot-analyze.yml
.github/workflows/springboot-step-tests-mysql.yml
.github/workflows/springboot-step-tests.yml
.github/workflows/springboot-workflow-common.yml
README.md

feat: add maven settings

---

.github/workflows/springboot-workflow-common.yml

chore: make RUN_ON and RUNNERS_CONTAINER_GROUP optional in springboot workflow common

---

.github/workflows/springboot-workflow-common.yml

fix: fix release from spring common pr update

---

.github/workflows/docker-step-build-and-push-image.yml

feat: docker build and push add script pre build

---

.github/workflows/docker-step-build-and-push-image.yml
.github/workflows/pull-request.yml
.github/workflows/release.yml

fix: revert runner public
